title: "Esserco Avoink"
description: "Modern Jekyll Website Templates Solutions for small websites"
url: https://gan-fan-man.github.io
baseurl: /
avatar: avatar.jpeg
cover_image: bg.jpeg

pagination:
  enabled: true
  per_page: 10
  sort_field: 'date'
  sort_reverse: true

plugins:
  - jekyll-gist
  - jekyll-paginate-v2
  - jekyll-seo-tag
  - jekyll-feed
  - jekyll-sitemap
  - jemoji

exclude:
  - '.editorconfig'
  - '.git'
  - '.jekyll-cache'
  - 'Gemfile'
  - 'Gemfile.lock'
  - 'LICENSE.md'
  - 'README.md'
  - 'scripts/'
  - 'Ganfan_man_Pages.gemspec'

twitter:
  username: "Ganfan_man"
  card: summary

social:
  - {name: Twitter, url: https://twitter.com/Ganfan_man}
  - {name: GitHub, url: https://github.com/Gan-fan-man}

langs:
  - zh-Hans
  - en

sass:
  sass_dir: _sass
  style: compressed

author:
  name: "Ganfan_man"
  url: https://github.com/Gan-fan-man
  email: ganfan.man.2023@gmail.com

collections:
  tools:
    output: true
    permalink: /tools/:name/
