title: Ganfan_man
description: This project is Ganfan_man’s personal website
url: https://gan-fan-man.github.io
avatar: avatar.jpeg
paginate: 5
permalink: pretty
cover_image: bg.jpeg

plugins:
  - jekyll-gist
  - jekyll-paginate
  - jekyll-seo-tag
  - jekyll-feed
  - jekyll-sitemap

exclude:
  - .editorconfig
  - .git
  - .jekyll-cache
  - Gemfile
  - Gemfile.lock
  - LICENSE.md
  - README.md
  - scripts/
  - not-pure-poole.gemspec

twitter:
  username: Ganfan_man
  card: summary
logo: logo.png
social:
  name: Ganfan_man
  links:
    - https://twitter.com/Ganfan_man
    - https://github.com/Gan-fan-man

lang: zh-cn
sass:
  sass_dir: _sass
  style: :compressed

author:
  name: Ganfan_man
  url: https://github.com/Gan-fan-man
  email: Ganfan_man@protonmail.com
