name: Release notes

on:
  push:
    branches:
      - master
  schedule:
    - cron: 0 19 * * *

jobs:
  update_release_draft:
    runs-on: ubuntu-latest
    env:
      RUBY_VERSION: 3.3.6
      JEKYLL_VERSION: 3.10.0
    steps:
      - name: Update release draft
        id: update_release_draft
        uses: release-drafter/release-drafter@v5
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  deploy_pages:
    runs-on: ubuntu-latest
    env:
      RUBY_VERSION: 3.3.6
      JEKYLL_VERSION: 3.10.0
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Tree GITHUB_WORKSPACE directory
        run: tree $GITHUB_WORKSPACE
      - name: Print GITHUB_WORKSPACE directory
        run: echo "$(tree $GITHUB_WORKSPACE)"
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./_site
          publish_branch: master
