name: Release notes

on:
  push:
    branches:
      - master
  schedule:
    - cron: 0 19 * * *
jobs:
  update_release_draft:
    runs-on: ubuntu-latest
    env:
      RUBY_VERSION: 3.3.6
      JEKYLL_VERSION: 3.10.0
    steps:
      - name: Update release draft
        uses: release-drafter/release-drafter@v5
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        outputs:
          draft: ${{ steps.update_release_draft.outputs.draft }}
      - name: Post release draft
        uses: github-actions/post-release-draft@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        inputs:
          draft: ${{ steps.update_release_draft.outputs.draft }}
          name: Release notes


jobs:
  update_release_draft:
    runs-on: ubuntu-latest
    env:
      RUBY_VERSION: 3.3.6
      JEKYLL_VERSION: 3.10.0
    steps:
      - name: Update release draft
        uses: release-drafter/release-drafter@v5
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        outputs:
          draft: ${{ steps.update_release_draft.outputs.draft }}
      - name: Post release draft
        uses: github-actions/post-release-draft@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        inputs:
          draft: ${{ steps.update_release_draft.outputs.draft }}
  deploy_pages:
    runs-on: ubuntu-latest
    env:
      RUBY_VERSION: 3.3.6
      JEKYLL_VERSION: 3.10.0
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Tree GITHUB_WORKSPACE directory
        run: tree $GITHUB_WORKSPACE
      - name: Tree GITHUB_WORKSPACE directory
        run: echo "$(tree $GITHUB_WORKSPACE)"
      - name: Deploy to GitHub Pages
        uses: github-pages/deploy@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          folder: .
          target_branch: master